/// Realistic starter dataset for a small Pakistani distributor ("Malik"),
/// priced in Pakistani Rupees.
///
/// Unlike [SampleData] (the tiny Appendix A test fixture), this is a believable
/// shop with a full catalog, several salespersons, and three months of
/// movements so the dashboard, periods, and reports all show meaningful data.
///
/// The transaction stream is generated by a stock-tracking builder, so a sale
/// can never exceed available stock and balances stay sensible.
library;

import 'models.dart';

class DemoBuild {
  final List<Product> products;
  final List<Salesperson> salespersons;
  final List<Txn> txns;
  final Set<String> brands;
  final Set<String> categories;
  final Set<String> sizes;
  final Set<String> expenseCategories;
  const DemoBuild({
    required this.products,
    required this.salespersons,
    required this.txns,
    required this.brands,
    required this.categories,
    required this.sizes,
    required this.expenseCategories,
  });
}

class DemoData {
  static const settings = StoreSettings(
    storeName: 'Malik',
    currency: 'Rs ', // Pakistani Rupees
    decimalPlaces: 0,
    openingCash: 700000,
    lowStock: 25,
  );

  // (id, code, name, brand, category, size, buy, sell, initialStock)
  static const _catalog = <List<Object>>[
    ['ts_m', 'TS-M', 'Cotton tee', 'Acme', 'T-shirts', 'M', 180, 280, 200],
    ['ts_l', 'TS-L', 'Cotton tee', 'Acme', 'T-shirts', 'L', 180, 280, 200],
    ['ts_xl', 'TS-XL', 'Cotton tee', 'Acme', 'T-shirts', 'XL', 190, 300, 120],
    ['vn_m', 'VN-M', 'V-neck tee', 'Acme', 'T-shirts', 'M', 200, 320, 90],
    ['vn_l', 'VN-L', 'V-neck tee', 'Acme', 'T-shirts', 'L', 200, 320, 90],
    ['sh7', 'SH-7', 'Runner shoe', 'Nova', 'Footwear', '7', 900, 1400, 35],
    ['sh8', 'SH-8', 'Runner shoe', 'Nova', 'Footwear', '8', 900, 1400, 45],
    ['sh9', 'SH-9', 'Runner shoe', 'Nova', 'Footwear', '9', 950, 1450, 28],
    ['tr8', 'TR-8', 'Trail shoe', 'Nova', 'Footwear', '8', 1100, 1700, 30],
    ['tr9', 'TR-9', 'Trail shoe', 'Nova', 'Footwear', '9', 1100, 1700, 24],
    ['cap', 'CP-S', 'Logo cap', 'Acme', 'Caps', 'Std', 90, 180, 300],
    ['hat', 'BH-S', 'Bucket hat', 'Acme', 'Caps', 'Std', 120, 240, 120],
    ['tote', 'BG-T', 'Canvas tote', 'Pioneer', 'Bags', 'Std', 150, 300, 150],
    ['bag', 'BG-P', 'Backpack', 'Pioneer', 'Bags', 'Std', 600, 1100, 50],
    ['bulb', 'HM-B', 'LED bulb', 'Bright', 'Home', 'Std', 70, 130, 400],
    ['cord', 'HM-C', 'Extension cord', 'Bright', 'Home', 'Std', 160, 280, 80],
    ['b500', 'BT-5', 'Steel bottle', 'Zest', 'Bottles', '500ml', 220, 380, 100],
    ['b750', 'BT-7', 'Steel bottle', 'Zest', 'Bottles', '750ml', 260, 440, 80],
  ];

  // (id, name, opening, marginBp)
  static const _people = <List<Object>>[
    ['sp_bilal', 'Bilal Ahmed', 0, 0],
    ['sp_amir', 'Amir Khan', 0, 0],
    ['sp_sana', 'Sana Iqbal', 0, 0],
    ['sp_ayesha', 'Ayesha Siddiqui', 6000, 2000], // owed at start, 20% margin
    ['sp_usman', 'Usman Tariq', 0, 0],
    ['sp_hina', 'Hina Malik', 3000, 0],
  ];

  static String _d(int year, int month, int day) {
    // Normalise (e.g. month 0 -> previous December).
    final base = DateTime(year, month, day);
    final m = base.month.toString().padLeft(2, '0');
    final dd = base.day.toString().padLeft(2, '0');
    return '${base.year}-$m-$dd';
  }

  /// Builds the full demo dataset relative to [now] so it always looks recent:
  /// stock-in two months ago, then sales/returns/payments/expenses across the
  /// last three months including the current one.
  static DemoBuild build(DateTime now, {required int createdBase}) {
    final products = <Product>[];
    final priceOf = <String, ({int buy, int sell})>{};
    final stock = <String, int>{};
    for (final c in _catalog) {
      final id = c[0] as String;
      final buy = c[6] as int;
      final sell = c[7] as int;
      products.add(Product(
        id: id,
        code: c[1] as String,
        name: c[2] as String,
        brand: c[3] as String,
        category: c[4] as String,
        size: c[5] as String,
        buyPrice: buy,
        sellPrice: sell,
        createdAt: createdBase,
      ));
      priceOf[id] = (buy: buy, sell: sell);
      stock[id] = 0;
    }

    final salespersons = [
      for (final p in _people)
        Salesperson(
          id: p[0] as String,
          name: p[1] as String,
          opening: p[2] as int,
          openingMarginBp: p[3] as int,
          createdAt: createdBase,
        ),
    ];

    var clock = createdBase;
    int nextClock() => clock += 1000;
    final txns = <Txn>[];
    var seq = 0;
    String nextId(String prefix) => '${prefix}_${seq++}';

    // Month anchors.
    final y = now.year;
    final mo = now.month;
    String m2(int day) => _d(y, mo - 2, day);
    String m1(int day) => _d(y, mo - 1, day);
    String m0(int day) => _d(y, mo, day.clamp(1, now.day));

    // ---- Initial stock-in (two months ago) --------------------------------
    void stockIn(String pid, int qty, String date) {
      stock[pid] = (stock[pid] ?? 0) + qty;
      txns.add(Txn(
        id: nextId('si'),
        type: TxnType.stockin,
        date: date,
        createdAt: nextClock(),
        productId: pid,
        qty: qty,
        unitBuy: priceOf[pid]!.buy,
      ));
    }

    for (final c in _catalog) {
      stockIn(c[0] as String, c[8] as int, m2(3));
    }
    // A mid-cycle restock of fast movers, last month.
    stockIn('cap', 150, m1(8));
    stockIn('ts_m', 80, m1(8));
    stockIn('bulb', 200, m1(8));

    // ---- Sales (qty is capped at available stock) --------------------------
    final balance = {for (final s in salespersons) s.id: s.opening};

    void sale(String sp, String date, List<(String, int)> want) {
      final lines = <TxnLine>[];
      final id = nextId('sale');
      for (final (pid, q) in want) {
        final avail = stock[pid] ?? 0;
        final qty = q <= avail ? q : avail;
        if (qty <= 0) continue;
        stock[pid] = avail - qty;
        final pr = priceOf[pid]!;
        lines.add(TxnLine(
          id: '${id}_$pid',
          transactionId: id,
          productId: pid,
          qty: qty,
          unitSell: pr.sell,
          unitBuy: pr.buy,
        ));
      }
      if (lines.isEmpty) return;
      final total = lines.fold(0, (s, l) => s + l.lineSell);
      balance[sp] = (balance[sp] ?? 0) + total;
      txns.add(Txn(
        id: id,
        type: TxnType.sale,
        date: date,
        createdAt: nextClock(),
        salespersonId: sp,
        lines: lines,
      ));
    }

    void returnGoods(String sp, String date, List<(String, int)> items) {
      final lines = <TxnLine>[];
      final id = nextId('ret');
      for (final (pid, q) in items) {
        stock[pid] = (stock[pid] ?? 0) + q;
        final pr = priceOf[pid]!;
        lines.add(TxnLine(
          id: '${id}_$pid',
          transactionId: id,
          productId: pid,
          qty: q,
          unitSell: pr.sell,
          unitBuy: pr.buy,
        ));
      }
      final total = lines.fold(0, (s, l) => s + l.lineSell);
      balance[sp] = (balance[sp] ?? 0) - total;
      txns.add(Txn(
        id: id,
        type: TxnType.returnGoods,
        date: date,
        createdAt: nextClock(),
        salespersonId: sp,
        lines: lines,
      ));
    }

    void payment(String sp, int amount, String date) {
      final amt = amount.clamp(0, balance[sp] ?? 0);
      if (amt <= 0) return;
      balance[sp] = (balance[sp] ?? 0) - amt;
      txns.add(Txn(
        id: nextId('pay'),
        type: TxnType.payment,
        date: date,
        createdAt: nextClock(),
        salespersonId: sp,
        amount: amt,
      ));
    }

    // Two months ago — first round of distribution.
    sale('sp_bilal', m2(6), [('ts_m', 40), ('cap', 60), ('tote', 20)]);
    sale('sp_amir', m2(7), [('sh7', 8), ('sh8', 10), ('bag', 6)]);
    sale('sp_sana', m2(9), [('ts_l', 30), ('vn_m', 15), ('hat', 20)]);
    sale('sp_ayesha', m2(10), [('b500', 25), ('b750', 15)]);
    sale('sp_usman', m2(12), [('bulb', 120), ('cord', 30)]);
    payment('sp_bilal', 9000, m2(20));
    payment('sp_amir', 12000, m2(22));
    payment('sp_sana', 5000, m2(24));

    // Last month — repeat orders, payments, a return.
    sale('sp_bilal', m1(4), [('ts_m', 35), ('cap', 50)]);
    sale('sp_amir', m1(5), [('sh8', 6), ('sh9', 7), ('tr8', 5)]);
    sale('sp_sana', m1(6), [('ts_l', 25), ('vn_l', 18)]);
    sale('sp_ayesha', m1(9), [('b500', 20), ('tote', 30)]);
    sale('sp_usman', m1(11), [('bulb', 150), ('bulb', 0)]);
    sale('sp_hina', m1(14), [('bag', 10), ('hat', 25)]);
    returnGoods('sp_amir', m1(16), [('tr8', 2)]);
    payment('sp_bilal', 14000, m1(20));
    payment('sp_amir', 15000, m1(21));
    payment('sp_sana', 9000, m1(23));
    payment('sp_ayesha', 8000, m1(25));
    payment('sp_usman', 16000, m1(26));

    // This month — current activity (some balances left open on purpose).
    sale('sp_bilal', m0(3), [('vn_m', 20), ('b500', 12)]);
    sale('sp_amir', m0(4), [('sh7', 6), ('cord', 15)]);
    sale('sp_sana', m0(5), [('cap', 40), ('ts_xl', 20)]);
    sale('sp_ayesha', m0(6), [('b750', 18), ('hat', 15)]);
    sale('sp_hina', m0(7), [('tote', 25), ('bulb', 60)]);
    sale('sp_usman', m0(9), [('bag', 8)]);
    returnGoods('sp_sana', m0(11), [('ts_xl', 3)]);
    payment('sp_bilal', 6000, m0(12));
    payment('sp_amir', 7000, m0(14));
    payment('sp_hina', 4000, m0(15));
    payment('sp_ayesha', 5000, m0(16));

    // ---- Expenses ----------------------------------------------------------
    void expense(String cat, int amount, String date, {bool recurring = false}) {
      txns.add(Txn(
        id: nextId('exp'),
        type: TxnType.expense,
        date: date,
        createdAt: nextClock(),
        category: cat,
        amount: amount,
        recurring: recurring,
      ));
    }

    for (final mk in [m2, m1, m0]) {
      expense('Rent', 18000, mk(1), recurring: true);
      expense('Electricity', 2400, mk(2), recurring: true);
      expense('Wages', 22000, mk(3), recurring: true);
    }
    expense('Transport', 1800, m2(15));
    expense('Packaging', 1200, m1(13));
    expense('Transport', 2100, m1(19));
    expense('Packaging', 900, m0(8));

    return DemoBuild(
      products: products,
      salespersons: salespersons,
      txns: txns,
      brands: {'Acme', 'Nova', 'Pioneer', 'Bright', 'Zest'},
      categories: {'T-shirts', 'Footwear', 'Caps', 'Bags', 'Home', 'Bottles'},
      sizes: {'M', 'L', 'XL', '7', '8', '9', 'Std', '500ml', '750ml'},
      expenseCategories: {
        'Rent',
        'Electricity',
        'Wages',
        'Transport',
        'Packaging',
      },
    );
  }
}
